### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by stevesoltys** [Mobe91/wit4j#2]
First off, thanks for working towards providing an API wrapper for wit.ai! It's just what I was looking for.

Proxy support is something that is missing and also something that I need for my use case. I couldn't find an easy way of setting a proxy for the client interface that you're using. If I find a solution (or if you happen to know of one), I will submit a pull request for this change.

**Comment by Mobe91** [comment]
Thanks for creating the issue.

Am I understanding you right: You want to set a custom HTTP (e.g.) proxy on the JAX-RS client that is used internally by `com.codelawine.wit4j.Wit`?

**Comment by Mobe91** [comment]
34365df9c1765be7edf3acc7fadc7ffe9d55491b adds the possibility to provide a custom ClientBuilder to `com.codelawine.wit4j.Wit` via `com.codelawine.wit4j.WitConfiguration.WitConfigurationBuilder#withProvidedClientBuilder`. JAX-RS defines no standard way for configuring a proxy for the client so letting the user provide a custom client builder is the easiest option.

Let me know if this works for you.

**Comment by stevesoltys** [comment]
Yes, that works for me. Thanks.

**Comment by Mobe91** [comment]
via 34365df
